apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seeder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rsiegfanz/home-control-2.git
    path: ops/apps/backend/seeder/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: home-control
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
