apiVersion: v1
kind: Secret
metadata:
  name: docker-secrets
  namespace: home-control
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "xx",
          "password": "xx",
          "email": "xx"
        }
      }
    }
