# Kafka Helm Chart Configuration for Single Pod in KRaft Mode

replicaCount: 1

kafka:
  enabled: true
  mode: kraft

  kraft:
    enabled: true
    replicationFactor: 1

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  storage:
    storageClassName: ""
    type: persistentVolumeClaim
    size: 10Gi
    accessMode: ReadWriteOnce
    existingClaim: kafka-pv-claim

  listeners:
    external:
      enabled: false
      port: 9094
      type: ClusterIP
    internal:
      enabled: true
      port: 9093

  schemaRegistry:
    enabled: false
  zookeeper:
    enabled: false
  connect:
    enabled: false
  ksqlDB:
    enabled: false

  log:
    level: INFO

  jmx:
    enabled: false
  consumerGroup:
    enabled: false
