apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rsiegfanz/home-control-2.git
    targetRevision: HEAD
    path: ops/helm/data_infrastructure/kafka
    helm:
      valueFiles:
        - values.yaml
      releaseName: kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
