apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rsiegfanz/home-control-2.git
    targetRevision: HEAD
    path: ops/helm/data_infrastructure/redis
    helm:
      valueFiles:
        - values.yaml
      releaseName: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
