replicaCount: 1

kafka:
  enabled: true
  mode: kraft

  controller:
    replicaCount: 1
    persistence:
      enabled: false

  kraft:
    enabled: true
    replicationFactor: 1

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"

  volumeClaimTemplate:
    enabled: false

  storage:
    storageClassName: ""
    type: persistentVolumeClaim
    size: 10Gi
    accessMode: ReadWriteOnce
    existingClaim: kafka-pv-claim

  listeners:
    internal:
      enabled: true
      port: 9092
    external:
      enabled: false

  auth:
    enabled: false

  sasl:
    enabled: false

  security:
    interBrokerProtocol: PLAINTEXT
    protocol: PLAINTEXT
    listenerSecurityProtocolMap: "CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

  schemaRegistry:
    enabled: false
  zookeeper:
    enabled: false
  connect:
    enabled: false
  ksqlDB:
    enabled: false

  log:
    level: INFO

  jmx:
    enabled: false
  consumerGroup:
    enabled: false
