apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  selector:
    app: coredns
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
