apiVersion: v1
kind: ConfigMap
metadata:
  name: fetcher-config
  namespace: home-control
data:
  URL: "xx"
  MODUS: "climate_current"
  POSTGRES_HOST: "timescaledb"
  POSTGRES_PORT: "5432"
  POSTGRES_DBNAME: "homecontrol"
  POSTGRES_USER: "home_control_user"
  KAFKA_HOST: kafka-service.kafka.svc.cluster.local:29092
