apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-deployment
  namespace: home-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
        - name: fetcher
          image: rsiegfanz/home-control-fetcher:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: fetcher-pv-claim
