apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeder-deployment
  namespace: home-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder
  template:
    metadata:
      labels:
        app: seeder
    spec:
      containers:
        - name: seeder
          image: rsiegfanz/home-control-seeder:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          envFrom:
            - configMapRef:
                name: seeder-config
            - configMapRef:
                name: kafka-connection-config
            - configMapRef:
                name: redis-connection-config
            - configMapRef:
                name: postgres-connection-config
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: seeder-pv-claim
