apiVersion: v1
kind: PersistentVolume
metadata:
  name: seeder-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100
    path: /srv/nfs_shared_folder/k8s/apps/seeder
