apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rsiegfanz/home-control.git
    targetRevision: HEAD
    path: ops/helm/monitoring/grafana
    helm:
      valueFiles:
        - values.yaml
      releaseName: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
