replicaCount: 1

postgresql:
  enabled: true
  architecture: standalone

  initContainers:
    - name: install-timescaledb
      image: bitnami/postgresql:16.2.3
      command:
        - /bin/bash
        - -c
        - |
          apt-get update
          apt-get install -y wget gnupg
          wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | apt-key add -
          sh -c "echo 'deb https://packagecloud.io/timescale/timescaledb/debian/ bullseye main' > /etc/apt/sources.list.d/timescaledb.list"
          apt-get update
          apt-get install -y timescaledb-2-postgresql-16
      securityContext:
        runAsUser: 0

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  persistence:
    enabled: true
    storageClassName: ""
    existingClaim: postgres-pv-claim
    size: 10Gi

  initdbScripts:
    enable-timescaledb.sql: |
      CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

  postgresqlConfiguration:
    shared_preload_libraries: timescaledb
    max_connections: 100

  auth:
    enablePostgresUser: true
    postgresPassword: "x"
    username: "homecontrol"
    password: "x"
    database: homecontrol

  primary:
    persistence:
      enabled: true
      storageClassName: ""
      existingClaim: postgres-pv-claim
      size: 10Gi
    extraVolumeMounts:
      - name: initdb-scripts
        mountPath: /docker-entrypoint-initdb.d
    extraVolumes:
      - name: initdb-scripts
        emptyDir: {}
