apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: home-control

resources:
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
