apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pv-claim
  namespace: home-control
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: server-pv
